/* eslint-disable import/no-anonymous-default-export */
export default {
    books: "Könyvek",
    chapterlist: "Fejezetlista / Szerkeztés",
    chapters: "Fejezetek",
    comments: "Hozzászólások",
    contexts: "Kontextusok",
    favourites: "Kedvencek",
    googleloginbutton: "Google bejelentkezés gomb",
    home: "Kezdőlap",
    iconselector: "Ikonválasztó",
    loading: "Betöltés",
    login: "Bejelentkezés",
    navbar: "Navigációs sáv",
    profile: "Profil",
    profilemenu: "Profilmenü",
    publishbook: "Könyv közzététele",
    raindropbackground: "Esőcsepp háttér",
    rankbar: "Rang sáv",
    rankicon: "Rang ikon",
    rankselector: "Rangválasztó",
    read: "Olvasás",
    register: "Regisztráció",
    requests: "Kérések",
    settings: "Beállítások",
    starrating: "Csillagos értékelés",
    themetoggle: "Téma váltó",
    toastnotification: "Értesítés",
    userinfo: "Felhasználói adatok",
};
